<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tyler Busby">
<meta name="dcterms.date" content="2025-03-24">

<title>Lab 5: Student Evaluations of Teaching</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lab-5-student_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab-5-student_files/libs/quarto-html/quarto.js"></script>
<script src="lab-5-student_files/libs/quarto-html/popper.min.js"></script>
<script src="lab-5-student_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab-5-student_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab-5-student_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab-5-student_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab-5-student_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab-5-student_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab-5-student_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 5: Student Evaluations of Teaching</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tyler Busby </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 24, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>In this lab, we will be using the <code>dplyr</code> package to explore student evaluations of teaching data.</p>
<p><strong>You are expected to use functions from <code>dplyr</code> to do your data manipulation!</strong></p>
<section id="part-1-github-workflow" class="level1">
<h1>Part 1: GitHub Workflow</h1>
<p>Now that you have the Lab 5 repository cloned, you need to make sure you can successfully push to GitHub. To do this you need to:</p>
<ul>
<li>Open the <code>lab-5-student.qmd</code> file (in the lower right hand corner).</li>
<li>Change the <code>author</code> line at the top of the document (in the YAML) to your name.</li>
<li>Save your file either by clicking on the blue floppy disk or with a shortcut (command / control + s).</li>
<li>Click the “Git” tab in upper right pane</li>
<li>Check the “Staged” box for the <code>lab-5-student.qmd</code> file (the file you changed)</li>
<li>Click “Commit”</li>
<li>In the box that opens, type a message in “Commit message”, such as “Added my name”.</li>
<li>Click “Commit”.</li>
<li>Click the green “Push” button to send your local changes to GitHub.</li>
</ul>
<p>RStudio will display something like:</p>
<pre><code>&gt;&gt;&gt; /usr/bin/git push origin HEAD:refs/heads/main
To https://github.com/atheobold/introduction-to-quarto-allison-theobold.git
   3a2171f..6d58539  HEAD -&gt; main</code></pre>
<p>Now you are ready to go! Remember, as you are going through the lab I would strongly recommend rendering your HTML and committing your after <strong>every</strong> question!</p>
</section>
<section id="part-2-some-words-of-advice" class="level1">
<h1>Part 2: Some Words of Advice</h1>
<p>Part of learning to program is learning from a variety of resources. Thus, I expect you will use resources that you find on the internet. There is, however, an important balance between copying someone else’s code and <em>using their code to learn</em>.</p>
<p>Therefore, if you use external resources, I want to know about it.</p>
<ul>
<li><p>If you used Google, you are expected to “inform” me of any resources you used by <strong>pasting the link to the resource in a code comment next to where you used that resource</strong>.</p></li>
<li><p>If you used ChatGPT, you are expected to “inform” me of the assistance you received by (1) indicating somewhere in the problem that you used ChatGPT (e.g., below the question prompt or as a code comment), and (2) downloading and including the <code>.txt</code> file containing your <strong>entire</strong> conversation with ChatGPT.</p></li>
</ul>
<p>Additionally, you are permitted and encouraged to work with your peers as you complete lab assignments, but <strong>you are expected to do your own work</strong>. Copying from each other is cheating, and letting people copy from you is also cheating. Please don’t do either of those things.</p>
<section id="setting-up-your-code-chunks" class="level2">
<h2 class="anchored" data-anchor-id="setting-up-your-code-chunks">Setting Up Your Code Chunks</h2>
<ul>
<li><p>The first chunk of this Quarto document should be used to <em>declare your libraries</em> (probably only <code>tidyverse</code> for now).</p></li>
<li><p>The second chunk of your Quarto document should be to <em>load in your data</em>.</p></li>
</ul>
</section>
<section id="save-regularly-render-often" class="level2">
<h2 class="anchored" data-anchor-id="save-regularly-render-often">Save Regularly, Render Often</h2>
<ul>
<li>Be sure to <strong>save</strong> your work regularly.</li>
<li>Be sure to <strong>render</strong> your file every so often, to check for errors and make sure it looks nice.
<ul>
<li>Make sure your Quarto document does not contain <code>View(dataset)</code> or <code>install.packages("package")</code>, both of these will prevent rendering.</li>
<li>Check your Quarto document for occasions when you looked at the data by typing the name of the data frame. Leaving these in means the whole dataset will print out and this looks unprofessional. <strong>Remove these!</strong></li>
<li>If all else fails, you can set your execution options to <code>error: true</code>, which will allow the file to render even if errors are present.</li>
</ul></li>
</ul>
</section>
</section>
<section id="part-3-lets-start-working-with-the-data" class="level1">
<h1>Part 3: Let’s Start Working with the Data!</h1>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>The <code>teacher_evals</code> dataset contains student evaluations of reaching (SET) collected from students at a University in Poland. There are SET surveys from students in all fields and all levels of study offered by the university.</p>
<p>The SET questionnaire that every student at this university completes is as follows:</p>
<blockquote class="blockquote">
<p>Evaluation survey of the teaching staff of University of Poland. Please complete the following evaluation form, which aims to assess the lecturer’s performance. Only one answer should be indicated for each question. The answers are coded in the following way: 5 - I strongly agree; 4 - I agree; 3 - Neutral; 2 - I don’t agree; 1 - I strongly don’t agree.</p>
<p>Question 1: I learned a lot during the course.</p>
<p>Question 2: I think that the knowledge acquired during the course is very useful.</p>
<p>Question 3: The professor used activities to make the class more engaging.</p>
<p>Question 4: If it was possible, I would enroll for a course conducted by this lecturer again.</p>
<p>Question 5: The classes started on time.</p>
<p>Question 6: The lecturer always used time efficiently.</p>
<p>Question 7: The lecturer delivered the class content in an understandable and efficient way.</p>
<p>Question 8: The lecturer was available when we had doubts.</p>
<p>Question 9. The lecturer treated all students equally regardless of their race, background and ethnicity.</p>
</blockquote>
<p>These data are from the end of the winter semester of the 2020-2021 academic year. In the period of data collection, all university classes were entirely online amid the COVID-19 pandemic. While expected learning outcomes were not changed, the online mode of study could have affected grading policies and could have implications for data.</p>
<p><strong>Average SET scores</strong> were combined with many other variables, including:</p>
<ol type="1">
<li><strong>characteristics of the teacher</strong> (degree, seniority, gender, SET scores in the past 6 semesters).</li>
<li><strong>characteristics of the course</strong> (time of day, day of the week, course type, course breadth, class duration, class size).</li>
<li><strong>percentage of students providing SET feedback.</strong></li>
<li><strong>course grades</strong> (mean, standard deviation, percentage failed for the current course and previous 6 semesters).</li>
</ol>
<p>This rich dataset allows us to <strong>investigate many of the biases in student evaluations of teaching</strong> that have been reported in the literature and to formulate new hypotheses.</p>
<p>Before tackling the problems below, study the description of each variable included in the <code>teacher_evals_codebook.pdf</code>.</p>
<p><strong>1. Load the appropriate R packages for your analysis.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#load tidyverse package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic) <span class="co">#loads mosaic package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2

The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.

Attaching package: 'mosaic'

The following object is masked from 'package:Matrix':

    mean

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:purrr':

    cross

The following object is masked from 'package:ggplot2':

    stat

The following objects are masked from 'package:stats':

    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum</code></pre>
</div>
</div>
<p><strong>2. Load in the <code>teacher_evals</code> data.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>teacher_evals <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data-raw/teacher_evals.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 8015 Columns: 22
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): course_id, weekday, time_of_day, academic_degree, gender
dbl (17): teacher_id, question_no, no_participants, resp_share, SET_score_av...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="data-inspection-summary" class="level3">
<h3 class="anchored" data-anchor-id="data-inspection-summary">Data Inspection + Summary</h3>
<p><strong>3. Provide a brief overview (~4 sentences) of the dataset.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(teacher_evals) <span class="co">#shows first 5 lines of the dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 22
  course_id  teacher_id question_no no_participants resp_share SET_score_avg
  &lt;chr&gt;           &lt;dbl&gt;       &lt;dbl&gt;           &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1 0000-BHP        54655         901             255     0.212           4.22
2 0000-BHP        54655         903             255     0.208           3.68
3 0000-BHP        54655         904             255     0.212           3.74
4 0000-BHP        54655         905             255     0.208           3.30
5 0000-BHP        54655         907             255     0.208           3.68
6 0000-BW-NP       3432         902             998     0.0411          4.05
# ℹ 16 more variables: stud_grade_avg &lt;dbl&gt;, stud_grade_std &lt;dbl&gt;,
#   stud_grade_var_coef &lt;dbl&gt;, percent_failed &lt;dbl&gt;, stud_grade_avg_cur &lt;dbl&gt;,
#   stud_grade_std_cur &lt;dbl&gt;, stud_grade_var_coef_cur &lt;dbl&gt;,
#   percent_failed_cur &lt;dbl&gt;, class_duration &lt;dbl&gt;, weekday &lt;chr&gt;,
#   time_of_day &lt;chr&gt;, SET_score_1sem &lt;dbl&gt;, maximum_score &lt;dbl&gt;,
#   academic_degree &lt;chr&gt;, seniority &lt;dbl&gt;, gender &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(teacher_evals) <span class="co">#shows number of rows in the dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8015</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(teacher_evals) <span class="co">#gives summary of the dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  course_id           teacher_id      question_no  no_participants  
 Length:8015        Min.   :  3432   Min.   :901   Min.   :   1.00  
 Class :character   1st Qu.: 38606   1st Qu.:903   1st Qu.:  15.00  
 Mode  :character   Median : 50752   Median :905   Median :  27.00  
                    Mean   : 49964   Mean   :905   Mean   :  46.95  
                    3rd Qu.: 66076   3rd Qu.:907   3rd Qu.:  50.00  
                    Max.   :110292   Max.   :909   Max.   :1003.00  
                                                   NA's   :34       
   resp_share      SET_score_avg   stud_grade_avg  stud_grade_std  
 Min.   :0.00348   Min.   :1.000   Min.   :2.375   Min.   :0.0000  
 1st Qu.:0.06061   1st Qu.:4.000   1st Qu.:3.583   1st Qu.:0.6369  
 Median :0.10000   Median :4.667   Median :4.015   Median :0.8562  
 Mean   :0.14020   Mean   :4.392   Mean   :3.962   Mean   :0.8078  
 3rd Qu.:0.16667   3rd Qu.:5.000   3rd Qu.:4.392   3rd Qu.:1.0100  
 Max.   :1.00000   Max.   :5.000   Max.   :5.000   Max.   :1.7678  
 NA's   :34                        NA's   :41      NA's   :41      
 stud_grade_var_coef percent_failed    stud_grade_avg_cur stud_grade_std_cur
 Min.   :0.0000      Min.   :0.00000   Min.   :2.375      Min.   :0.0000    
 1st Qu.:0.1483      1st Qu.:0.00000   1st Qu.:3.583      1st Qu.:0.5632    
 Median :0.2150      Median :0.07692   Median :4.048      Median :0.8311    
 Mean   :0.2120      Mean   :0.12490   Mean   :3.990      Mean   :0.7907    
 3rd Qu.:0.2777      3rd Qu.:0.19048   3rd Qu.:4.450      3rd Qu.:1.0278    
 Max.   :0.5439      Max.   :0.75000   Max.   :5.000      Max.   :1.7678    
 NA's   :41          NA's   :41        NA's   :41         NA's   :41        
 stud_grade_var_coef_cur percent_failed_cur class_duration    weekday         
 Min.   :0.0000          Min.   :0.0000     Min.   :0.000   Length:8015       
 1st Qu.:0.1325          1st Qu.:0.0000     1st Qu.:1.000   Class :character  
 Median :0.2107          Median :0.0723     Median :2.000   Mode  :character  
 Mean   :0.2073          Mean   :0.1274     Mean   :1.564                     
 3rd Qu.:0.2795          3rd Qu.:0.2000     3rd Qu.:2.000                     
 Max.   :0.5439          Max.   :0.7500     Max.   :3.000                     
 NA's   :41              NA's   :41         NA's   :914                       
 time_of_day        SET_score_1sem  maximum_score    academic_degree   
 Length:8015        Min.   :1.220   Min.   :0.0000   Length:8015       
 Class :character   1st Qu.:4.119   1st Qu.:0.0000   Class :character  
 Mode  :character   Median :4.471   Median :0.0000   Mode  :character  
                    Mean   :4.388   Mean   :0.4131                     
                    3rd Qu.:4.685   3rd Qu.:1.0000                     
                    Max.   :5.000   Max.   :1.0000                     
                    NA's   :697                                        
   seniority         gender         
 Min.   : 1.000   Length:8015       
 1st Qu.: 2.000   Class :character  
 Median : 6.000   Mode  :character  
 Mean   : 5.496                     
 3rd Qu.: 8.000                     
 Max.   :11.000                     
                                    </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>“teacher_evals” is a dataset comprised of 22 columns of variables and 8015 rows of cases. The variables include the characteristics of the teacher (teacher_id, seniority, and gender), characteristics of the course (time_of_day, weekday, and class_duration), response share (no_participants and resp_share), course grade information (stud_grade_avg, stud_grade_std, stud_grade_var_coef, percent_failed, stud_grade_avg_cur, stud_grade_std_cur, stud_grade_var_coef_cur, and percent_failed_cur), and SET score information (question_no, SET_score_avg, SET_score_1sem, and maximum_score). Most variables are numeric doubles, with the exception of course_id, weekday, time_of_day, academic_degree, gender, and teacher_id, which is wrongly classified as a double by R. There are a number of NA values in the dataset: 34 in no_participants and resp_share; 41 in stud_grade_avg, stud_grade_std, stud_grade_var_coef, percent_failed, stud_grade_avg_cur, stud_grade_std_cur, stud_grade_var_coef_cur, and percent_failed_cur; 914 in class_duration; and 697 for SET_score_1sem.</p>
</blockquote>
<p><strong>4. What is the unit of observation (i.e.&nbsp;a single row in the dataset) identified by?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(teacher_evals) <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(teacher_id) <span class="co">#shows first 5 lines of the dataset arranged by teacher_id</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 22
  course_id  teacher_id question_no no_participants resp_share SET_score_avg
  &lt;chr&gt;           &lt;dbl&gt;       &lt;dbl&gt;           &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1 0000-BW-NP       3432         902             998     0.0411          4.05
2 0000-BHP        54655         901             255     0.212           4.22
3 0000-BHP        54655         903             255     0.208           3.68
4 0000-BHP        54655         904             255     0.212           3.74
5 0000-BHP        54655         905             255     0.208           3.30
6 0000-BHP        54655         907             255     0.208           3.68
# ℹ 16 more variables: stud_grade_avg &lt;dbl&gt;, stud_grade_std &lt;dbl&gt;,
#   stud_grade_var_coef &lt;dbl&gt;, percent_failed &lt;dbl&gt;, stud_grade_avg_cur &lt;dbl&gt;,
#   stud_grade_std_cur &lt;dbl&gt;, stud_grade_var_coef_cur &lt;dbl&gt;,
#   percent_failed_cur &lt;dbl&gt;, class_duration &lt;dbl&gt;, weekday &lt;chr&gt;,
#   time_of_day &lt;chr&gt;, SET_score_1sem &lt;dbl&gt;, maximum_score &lt;dbl&gt;,
#   academic_degree &lt;chr&gt;, seniority &lt;dbl&gt;, gender &lt;chr&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The dataset is organized by question per teacher_id, so one row responds to one question for a given teacher.</p>
</blockquote>
<p><strong>5. Use <em>one</em> <code>dplyr</code> pipeline to clean the data by:</strong></p>
<ul>
<li><strong>renaming the <code>gender</code> variable <code>sex</code></strong></li>
<li><strong>removing all courses with fewer than 10 respondents</strong></li>
<li><strong>changing data types in whichever way you see fit (e.g., is the instructor ID really a numeric data type?)</strong></li>
<li><strong>only keeping the columns we will use – <code>course_id</code>, <code>teacher_id</code>, <code>question_no</code>, <code>no_participants</code>, <code>resp_share</code>, <code>SET_score_avg</code>, <code>percent_failed_cur</code>, <code>academic_degree</code>, <code>seniority</code>, and <code>sex</code></strong></li>
</ul>
<p><strong>Assign your cleaned data to a new variable named <code>teacher_evals_clean</code> –- use these data going forward. Save the data as <code>teacher_evals_clean.csv</code> in the <code>data-clean</code> folder.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="ot">&lt;-</span> teacher_evals <span class="sc">|&gt;</span> <span class="co">#save new data as "teacher_evals_clean"</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"sex"</span> <span class="ot">=</span> gender) <span class="sc">|&gt;</span> <span class="co">#rename gender variable to sex</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(no_participants <span class="sc">&gt;=</span> <span class="dv">10</span>) <span class="sc">|&gt;</span> <span class="co">#removing courses with &lt;10 respondents</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">teacher_id =</span> <span class="fu">as.character</span>(teacher_id)) <span class="sc">|&gt;</span> <span class="co">#sets teacher_id as a categorical variable</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(course_id, teacher_id, question_no, no_participants, resp_share, </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>         SET_score_avg, percent_failed_cur, academic_degree, seniority, sex) <span class="co">#select only desired variables</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(teacher_evals_clean, <span class="st">"data-clean/teacher_evals_clean.csv"</span>) <span class="co">#save dataset as csv in data-clean folder</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>6. How many unique instructors and unique courses are present in the cleaned dataset?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(teacher_id, course_id) <span class="sc">|&gt;</span> <span class="co">#find unique teachers and courses</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>() <span class="co">#count number</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      n
  &lt;int&gt;
1  1094</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>There are 1094 unique teacher and course combinations in the dataset.</p>
</blockquote>
<p><strong>7. One teacher-course combination has some missing values, coded as <code>NA</code>. Which instructor has these missing values? Which course? What variable are the missing values in?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_any</span>(<span class="at">.cols =</span> <span class="sc">-</span><span class="fu">c</span>(teacher_id, course_id), <span class="co">#filters for every column except teacher_id and course_id</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> is.na)) <span class="co">#finds any na values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 10
  course_id   teacher_id question_no no_participants resp_share SET_score_avg
  &lt;chr&gt;       &lt;chr&gt;            &lt;dbl&gt;           &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1 PAB3SE004PA 56347              901              32     0.0312             5
2 PAB3SE004PA 56347              902              32     0.0312             5
3 PAB3SE004PA 56347              903              32     0.0312             4
4 PAB3SE004PA 56347              905              32     0.0312             4
5 PAB3SE004PA 56347              906              32     0.0312             3
6 PAB3SE004PA 56347              907              32     0.0312             3
7 PAB3SE004PA 56347              908              32     0.0312             5
# ℹ 4 more variables: percent_failed_cur &lt;dbl&gt;, academic_degree &lt;chr&gt;,
#   seniority &lt;dbl&gt;, sex &lt;chr&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>It appears the teacher-course combination with na values is the the combination of teacher 56347 and course PAB3SE004PA. The value missing is percent_failed_cur.</p>
</blockquote>
<p><strong>8. What are the demographics of the instructors in this study? Investigate the variables <code>academic_degree</code>, <code>seniority</code>, and <code>sex</code> and summarize your findings in ~3 complete sentences.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(academic_degree) <span class="sc">|&gt;</span> <span class="co">#find counts teachers with each type of academic degree</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> n<span class="sc">/</span><span class="fu">nrow</span>(teacher_evals_clean)) <span class="co">#determines proportion of teachers with that degree type</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  academic_degree     n   prop
  &lt;chr&gt;           &lt;int&gt;  &lt;dbl&gt;
1 dr               4367 0.641 
2 ma               1852 0.272 
3 no_dgr            467 0.0685
4 prof              131 0.0192</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(seniority) <span class="sc">|&gt;</span> <span class="co">#counts teachers by years of seniority</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> n<span class="sc">/</span><span class="fu">nrow</span>(teacher_evals_clean)) <span class="sc">|&gt;</span> <span class="co">#determines proportion of teachers by seniority</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(prop)) <span class="co">#arrange by proportion with largest being at top</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
   seniority     n   prop
       &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
 1         2  1722 0.253 
 2         6   867 0.127 
 3         8   778 0.114 
 4        11   640 0.0939
 5         4   585 0.0858
 6         1   410 0.0601
 7         7   408 0.0599
 8        10   408 0.0599
 9         3   367 0.0538
10         9   352 0.0516
11         5   280 0.0411</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sex) <span class="sc">|&gt;</span> <span class="co">#find counts teachers by each sex</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> n<span class="sc">/</span><span class="fu">nrow</span>(teacher_evals_clean)) <span class="co">#determines proportion of teachers by sex</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  sex        n  prop
  &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;
1 female  3278 0.481
2 male    3539 0.519</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>In the dataset, a majority of the teachers listed are doctors, with 64.06% having a doctorate, 27.18% having a masters, 6.85% having no degrees, and 1.92% having a professional degree. Seniority showed that the largest percentage of teachers have 2 years of seniority with 25.26%, then 6 years, 8 years, 11 years, 4 years, 1 year, 7 years, 10 years, 3 years, 9 years, and 5 years being the smallest with a percentage of 4.11%. Finally, a the highest percentage of teachers were shown to be male, with a slim majority of 51.91%.</p>
</blockquote>
<p><strong>9. Each course seems to have used a different subset of the nine evaluation questions. How many teacher-course combinations asked all nine questions?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(teacher_id, course_id) <span class="sc">|&gt;</span> <span class="co">#groups by teacher and course id</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">questions_answered =</span> <span class="fu">count</span>(teacher_id, course_id)) <span class="sc">|&gt;</span> <span class="co">#determines number of questions answered by counting number of times each teacher-course combination appears (denoting a new question)</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(questions_answered <span class="sc">==</span> <span class="dv">9</span>) <span class="sc">|&gt;</span> <span class="co">#selects only teachers who asked all 9 questions</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> <span class="co">#ungroups data to allow count function</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>() <span class="co">#counts number of unique teacher-course combinations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'teacher_id'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      n
  &lt;int&gt;
1    49</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Only 49 teacher-course combinations asked all 49 questions.</p>
</blockquote>
</section>
</section>
<section id="rate-my-professor" class="level2">
<h2 class="anchored" data-anchor-id="rate-my-professor">Rate my Professor</h2>
<p><strong>10. Which instructors had the highest and lowest average rating for Question 1 (I learnt a lot during the course.) across all their courses?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(question_no <span class="sc">==</span> <span class="dv">901</span>) <span class="sc">|&gt;</span> <span class="co">#filter for only question 1</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(teacher_id) <span class="sc">|&gt;</span> <span class="co">#group by teacher</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_SET_score_avg =</span> <span class="fu">mean</span>(SET_score_avg)) <span class="sc">|&gt;</span> <span class="co">#determine average SET score across all classes</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mean_SET_score_avg <span class="sc">==</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>)) <span class="sc">|&gt;</span> <span class="co">#only select teachers with a mean score of 1 or 5</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean_SET_score_avg) <span class="co">#arranges by SET score average</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `filter()`.
ℹ In argument: `mean_SET_score_avg == c(1, 5)`.
Caused by warning in `mean_SET_score_avg == c(1, 5)`:
! longer object length is not a multiple of shorter object length</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 43 × 2
   teacher_id mean_SET_score_avg
   &lt;chr&gt;                   &lt;dbl&gt;
 1 54201                       1
 2 105217                      5
 3 106429                      5
 4 3471                        5
 5 3608                        5
 6 3662                        5
 7 3682                        5
 8 37013                       5
 9 37023                       5
10 37026                       5
# ℹ 33 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>In the dataset, 42 teachers recieved the maximum average rating of 5 for question 1 across all their courses, while only 1, teacher 54201, recieved the lowest average rating of 1 across all their courses.</p>
</blockquote>
<p><strong>11. Which instructors with one year of experience had the highest and lowest average percentage of students failing in the current semester across all their courses?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(seniority <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="co">#filter for only 1st year teachers</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(teacher_id) <span class="sc">|&gt;</span> <span class="co">#group by teacher</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_percent_failed_cur =</span> <span class="fu">mean</span>(percent_failed_cur)) <span class="sc">|&gt;</span> <span class="co">#determine percent failing across all classes</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean_percent_failed_cur) <span class="co">#arrange by number of students failing</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 33 × 2
   teacher_id mean_percent_failed_cur
   &lt;chr&gt;                        &lt;dbl&gt;
 1 102379                      0     
 2 103092                      0     
 3 106126                      0     
 4 86222                       0     
 5 98650                       0     
 6 98651                       0     
 7 105217                      0.025 
 8 84689                       0.0408
 9 80974                       0.0556
10 98652                       0.0662
# ℹ 23 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>In the dataset, 6 teachers are tied for the lowest percentage of students failing at 0.00%: teacher 102379, 103092, 106126, 86222, 98650, and 98651. The teacher with the highest percentage of students failing is teacher 106692 with 68.00% of students failing.</p>
</blockquote>
<p><strong>12. Which female instructors with either a doctorate or professional degree had the highest and lowest average percent of students responding to the evaluation across all their courses?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"female"</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>         academic_degree <span class="sc">==</span> <span class="fu">c</span>(<span class="st">"dr"</span>, <span class="st">"prof"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(teacher_id) <span class="sc">|&gt;</span> <span class="co">#group by teacher</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_resp_share =</span> <span class="fu">mean</span>(resp_share)) <span class="sc">|&gt;</span> <span class="co">#determine average percent response across all classes</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_resp_share)) <span class="sc">|&gt;</span> <span class="co">#arrange by mean percent response with highest at top</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>) <span class="co">#look at the top 5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `filter()`.
ℹ In argument: `academic_degree == c("dr", "prof")`.
Caused by warning in `academic_degree == c("dr", "prof")`:
! longer object length is not a multiple of shorter object length</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  teacher_id mean_resp_share
  &lt;chr&gt;                &lt;dbl&gt;
1 101508               0.522
2 66292                0.347
3 66289                0.259
4 76408                0.25 
5 60947                0.221</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>teacher_evals_clean <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"female"</span>,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>         academic_degree <span class="sc">==</span> <span class="fu">c</span>(<span class="st">"dr"</span>, <span class="st">"prof"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(teacher_id) <span class="sc">|&gt;</span> <span class="co">#group by teacher</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_resp_share =</span> <span class="fu">mean</span>(resp_share)) <span class="sc">|&gt;</span> <span class="co">#determine average percent response across all classes</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean_resp_share) <span class="sc">|&gt;</span> <span class="co">#arrange by mean percent response with lowest at top</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>) <span class="co">#look at the top 5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `filter()`.
ℹ In argument: `academic_degree == c("dr", "prof")`.
Caused by warning in `academic_degree == c("dr", "prof")`:
! longer object length is not a multiple of shorter object length</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  teacher_id mean_resp_share
  &lt;chr&gt;                &lt;dbl&gt;
1 59338               0.0148
2 42362               0.0310
3 50714               0.0312
4 42591               0.0388
5 56345               0.0456</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The teacher with the highest percentage of responses across all their classes was teacher 101508 with a 52.17% of their students responding, and the teacher with the lowest percentage of responses across all their classes was teacher 56345 with a 4.56% of their students responding.</p>
</blockquote>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>